---
# code: language=ansible
- name: Import dependency task
  ansible.builtin.import_tasks:
    file: dependency.yml
  tags:
    - role_goaccess_dependency
- name: Import repository task
  ansible.builtin.import_tasks:
    file: repository.yml
  tags:
    - role_goaccess_repository
- name: Import package task
  ansible.builtin.import_tasks:
    file: package.yml
  tags:
    - role_goaccess_package
- name: Import setting task
  ansible.builtin.import_tasks:
    file: setting.yml
  tags:
    - role_goaccess_setting
