---
# code: language=ansible
- name: Verify
  hosts: all
  gather_facts: false
  # check_mode: true
  become: true
  tasks:
    ## パッケージのテスト
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Assert package
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['goaccess'] is defined
          - ansible_facts.packages['geoipupdate'] is not defined
    # ファイルのテスト
    ## geoipupdateの設定ファイル
    - name: Check geoipupdate config file
      ansible.builtin.stat:
        path: /etc/GeoIP.conf
      register: stat_result
    - name: Assert geoipupdate config file
      ansible.builtin.assert:
        that:
          - not stat_result.stat.exists
    ## GeoIPデータベースの自動更新の設定
    - name: Check cron job file
      ansible.builtin.stat:
        path: /etc/cron.weekly/geoipupdate
      register: stat_result
    - name: Assert cron job file
      ansible.builtin.assert:
        that:
          - not stat_result.stat.exists
    ## GoAccessのGeoIPデータベースの設定
    - name: Assert goaccess geoip-database setting
      ansible.builtin.lineinfile:
        path: /etc/goaccess/goaccess.conf
        line: "#geoip-database /usr/share/GeoIP/GeoLite2-City.mmdb"
      register: lineinfile_result
      check_mode: true
    - name: Assert geoipupdate config file
      ansible.builtin.assert:
        that:
          - lineinfile_result is not changed
