---
# code: language=ansible
- name: Install goaccess packages
  ansible.builtin.apt:
    name: "{{ goaccess_packages }}"
- name: Install geoipupdate dependency packages
  when: goaccess_install_geoipupdate
  block:
    - name: Get latest release
      ansible.builtin.uri:
        url: https://api.github.com/repos/maxmind/geoipupdate/releases/latest
        headers:
          Accept: application/vnd.github+json
      register: latest_releases
    - name: Set tbls_version variable
      ansible.builtin.set_fact:
        geoipupdate_version: "{{ latest_releases.json.tag_name }}"
    - name: Set package file name parts variables
      ansible.builtin.set_fact:
        package_file_version: "{{ geoipupdate_version[1:] }}"
        package_file_system: "{{ ansible_facts['system'] | lower }}"
        package_file_architecture: "{{ architecture_files[ansible_facts['architecture']] }}"
      vars:
        architecture_files:
          x86_64: amd64
    - name: Set variable
      ansible.builtin.set_fact:
        package_file: geoipupdate_{{ package_file_version }}_{{ package_file_system }}_{{ package_file_architecture }}.deb
    - name: Install geoipupdate
      ansible.builtin.apt:
        deb: https://github.com/maxmind/geoipupdate/releases/download/{{ geoipupdate_version }}/{{ package_file }}
